version: "3.9"

services:
  postgres:
    image: postgres:18
    container_name: postgres18
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: stories
    ports:
      - "5432:5432"
    volumes:
      - pg18-data:/var/lib/postgresql

  api:
    container_name: api
    image: read-story:latest
    environment:
      DATABASE_URL: postgres://root:admin123@postgres:5432/stories
      PORT: 8080
    ports:
      - "8080:8080"

volumes:
  pg18-data:
