spring:
  application:
    name: Read Story Application
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/stories
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:admin123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

server:
  port: ${PORT:8082}

#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: TRACE

story:
  base-url: ${STORY_BASE_URL:https://truyenfull.vision}